from rest_base.errors import Error


users = Error('users')

# Register your own errors here
# SOMETHING_WENT_WRONG = users('SomethingWentWrong')
